### ISSUE TITLE
Update velocity bug

### ISSUE THREAD

**Issue by chen-luke** [Artists-for-Humanity/space-invaders-phaser#12]
When the enemy drops from the left side of the wall to the next level, the update functions gets called multiple times. The value of child.x also gets modified, but we don't know why.
https://github.com/Artists-for-Humanity/space-invaders-phaser/blob/920786f683d49dfc9207cbb46bedac5a667c91ef/src/scripts/final.js#L139

**Comment by HandyDorceus** [comment]
This was resolved by referencing the physics body of the game object
