### ISSUE TITLE
Clarify width and height

### ISSUE THREAD

**Issue by itisjamied** [Artists-for-Humanity/space-invaders-phaser#13]
https://github.com/Artists-for-Humanity/space-invaders-phaser/blob/main/tutorial/step3.md?plain=1#L125

it would be nice to have an explanation of the width and height variables

**Comment by HandyDorceus** [comment]
In this case, width and height are not actually variables, they are actually characteristics used to set the configuration of our game which is stored inside the 'config' variable. Here is a link that explains this in more depth https://workshops.nuevofoundation.org/phaser-space-invaders-game/phaser-fundementals/. This link is also available in step03 of the tutorial.
